services:

  api:
    container_name: flowforge-api
    build:
      context: ./api
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - postgres
    env_file:
      - ./api/.env.development
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    networks:
      - flowforge-back-net
      - flowforge-bf-net

  web:
    container_name: flowforge-web
    build:
      context: ./web
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - api
    env_file:
      - ./web/.env.development
    volumes:
      - ./web:/app
    networks:
      - flowforge-bf-net
    ports:
      - "80:3000"
  

  postgres:
    container_name: flowforge-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./db/.env.db
    environment:
      - NODE_ENV=development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flowforge-bf-net


volumes:
  postgres_data:

networks:
  flowforge-back-net:
    driver: bridge
  flowforge-bf-net:
    driver: bridge